services:
  web-admin:
    build: ./web
    volumes:
      - ./web/src:/app/src
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cfg:/cfg
    command: ["bun", "run", "--watch", "src/index.ts"]
